### PR TITLE
New git directory structure

### PR DESCRIPTION
**Pull request by alex-maiorov**

### CODE REVIEW

**Comment by alex-maiorov** [comment]
Hello, this is the branch with the cleaned out PCB directory tree. Since the purpose of the git structure is to make contributing easier, I would like feedback on this.

**Review by gautamdayal — APPROVED** [review]
Since it's just organizational stuff, LGTM. I'd wait for more reviews since I'm not too familiar with the structure pre-cleanup.

**Review by ben-olaivar — CHANGES_REQUESTED** [review]
- Not sure if we're going with the MK-4 name yet. You can keep it for now but I wouldn't get too attached (MK-3, rev-B or something will be more likely)
- Hierarchy may be confusing to some. "battery_management" overlaps with "regulators" quite a bit. Would recommend an overall "Power_management", with blue boxes/labels surrounding each regulator. Meet with me for more details
- regulators don't need their own schematic (a bit too smol to justify. Even with smd stuff)
- Think about how these hierarchy sections will connect to each other

**Review by Peter-Giannetos — COMMENTED** [review]
I still like the reorganization, but I had some more thoughts.

- Could we try to get a working record of TARS Mk. 1 & 2 set up under the boards folder?
- Also we should implement some kind of version control/revision structure, because the telemetry MK.3  PCB file is no longer the same board that flew at IREC. We accidentally didn't make a new branch/file when we started R&D. Could we find the archived PCB design that flew at IREC? The current telemetry PCB file could go under TARS Mk.3.1 folder.

I'm thinking we should merge this by Saturday morning just we can begin development on the altimeters PCBs.

**Comment by alex-maiorov** [comment]
> I still like the reorganization, but I had some more thoughts.
> 
>     * We should implement some kind of version control/revision structure, because the telemetry MK.3  PCB file is no longer the same board that flew at IREC. We accidentally didn't make a new branch/file when we started R&D. Could we find the archived PCB design that flew at IREC? The current telemetry PCB file could go under TARS Mk.3.1 folder.
> 
>     * Could we try to get a working record of TARS Mk. 1 & 2 set up under the boards folder? It's not needed immediately but I think it would be good for history/record keeping
> 
> 
> I'm thinking we should merge this by Saturday morning just we can begin development on the altimeters PCBs.

I will look for it, but i'm 90% sure that we scrapped the changes we were gonna do to TELEM. They were in a branch we deleted. I'll figure it out so its properly organized per what flew and what didn't and version accordingly. I can also forward port MK1 and MK2.

**Comment by alex-maiorov** [comment]
FYI I think forward porting MK1 and MK2 can wait until its merged. I'll just do it on a separate branch once this is in main.

**Comment by alex-maiorov** [comment]
ok I found the old boards, I adjusted the naming accordingly.

**Comment by Peter-Giannetos** [comment]
The telemetry board stuff looks good.

Yeah we don't need to dig up Mk1-2 right away - making another branch is fine.

I think this is good to merge. There's still some work to do with cleaning up the archive and such but I think that should be for a different PR.

**Review by Peter-Giannetos — APPROVED** [review]

**Comment by taojunglee** [comment]
I would prefer to have the "docs" folder in the "boards" folder. I assume the "boards" will be moved into archive after the folder for the next gen boards are created.

**Comment by alex-maiorov** [comment]
We aren't planning on archiving old boards. The archive is just a copy of the old files so we can work on forward porting it.

**Review by ben-olaivar — APPROVED** [review]
Approving the request but I'm personally still not a fan of the hierarchy. Would like to poll the team moving forward for this (current will result in very cluttered/numerous schematic files)

**Review by taojunglee — APPROVED** [review]
I would prefer to have the "docs" folder in the "boards" folder. I assume the "boards" will be moved into archive after the folder for the next gen boards are created.
This is a naming and moving stuff issue. no big deal.

**Pull request merged**
