### PR TITLE
mcubranch

### PR DESCRIPTION
**Pull request by Peter-Giannetos**
There's still some work to do but I'm just making this pull request for design discussion and such.

### CODE REVIEW

**Comment by Peter-Giannetos** [comment]
**Fixes**
- On the MCU schematic there appears to be some overlapping component labels. I think there could be some more uniformed spacing on the 3v3 power side.
- When connecting to a pin try to not make an immediate right angle turn. Instead extend it forward a bit and then turn if needed.

**To Do:**

- Finish/Clean-up any remaining power/ground connections
- Add an external TXCO to the MCU

**Comment by alex-maiorov** [comment]
^ please delete it after this is merged, make another branch and PR to delete this(plus other cruft files)

**Review by alex-maiorov — APPROVED** [review]
I think this can be merged now

**Comment by alex-maiorov** [comment]
Please re-create this branch and name it according to the currently used scheme of [trello ticket number]/[name-with-dashes]

**Pull request merged**
