### PR TITLE
AV-687/Altimeter-Power-Schematic

### PR DESCRIPTION
**Pull request by alex-maiorov**

### CODE REVIEW

**Review by eisha007 — APPROVED** [review]
Think this should be good for now, just waiting to add in the values for capacitance & resistance.

**Review by Peter-Giannetos — APPROVED** [review]
Looks good to me. When we're finalizing schematics I think we can clean it up further but it's good for now.

**Comment by Peter-Giannetos** [comment]
I'd merge this PR but then keep the branch open so we can continue to work on it if need be.

**Comment by alex-maiorov** [comment]
Cool cool. I merged it but keep using it for the ticket.

**Pull request merged**
