### PR TITLE
AV-693/Altimeter-GPS-Schematic

### PR DESCRIPTION
**Pull request by Peter-Giannetos**
The schematic looks mostly done, but there are a few style changes that need to be incorporated before merging.

- Title schematic (Bottom left corner)
- Add correct electrical characteristics to any labels (In,  Out, I/O etc.)
- Rename the schematic from "untitled" to "GPS", "GPS-Altimeter" or something similar.

### CODE REVIEW

**Comment by Peter-Giannetos** [comment]
We should also figure out what the merge conflicts are.

**Review by eisha007 — COMMENTED** [review]
I agree with Peter on his comments. Definitely change the Untitled to something more descriptive, and pertinent to GPS + Altimeters. Perhaps also using the text feature to add a note about the embedded antenna would be helpful to those unfamiliar with the SAM-M8Q. Also make sure that the size of the hierarchical sheet is the same as the others, to make the overall kicad schematic set look cleaner at anyone looking.

**Comment by alex-maiorov** [comment]
I renamed the file untitled.kicad_sch as part of me fixing the merge conflicts on this. Since this needed to modify the main schematic file, I want this merged as soon as everyone is okay with it.

**Review by alex-maiorov — APPROVED** [review]
We still need to add in the GPS heirarchical sheet into the main, I had to defer it as we did not have granular commits.

**Comment by Peter-Giannetos** [comment]
Given how small the GPS module wiring is would it be best to just include it in the sensors schematic?

**Comment by eisha007** [comment]
> Given how small the GPS module wiring is would it be best to just include it in the sensors schematic?

I think yes

**Comment by alex-maiorov** [comment]
Ok cool, can we merge this and reorganize afterwards? the merge conflicts would be very hard to deal with otherwise.

**Comment by eisha007** [comment]
> Ok cool, can we merge this and reorganize afterwards? the merge conflicts would be very hard to deal with otherwise.

Yes yes

**Pull request merged**
